# Generated by Django 4.2.4 on 2023-08-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgrado', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='course',
        ),
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.IntegerField(),
        ),
    ]
