# Generated by Django 4.2.4 on 2023-08-11 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postgrado', '0002_remove_teacher_course_alter_course_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='postgrado.course'),
        ),
    ]
