# Generated by Django 4.2.4 on 2023-08-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgrado', '0003_teacher_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Course',
            new_name='course',
        ),
    ]
