# Generated by Django 4.2.4 on 2023-08-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgrado', '0004_rename_course_student_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Career',
            new_name='career',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_status',
            new_name='courseStatus',
        ),
    ]
